WITH TEMP AS (
    SELECT ROW_NUMBER() OVER(ORDER BY LAT_N) AS ROW_NUM, LAT_N
    FROM STATION
    )
SELECT CAST(LAT_N AS DECIMAL(6,4)) AS MEDIAN_LAT_N
FROM TEMP
WHERE ROW_NUM = (((SELECT MAX(ROW_NUM) FROM TEMP) - (SELECT MIN(ROW_NUM) FROM TEMP))/2) + 1
