SELECT DOCTOR, PROFESSOR, SINGER, ACTOR
FROM
(SELECT ROW_NUMBER() OVER(PARTITION BY OCCUPATION ORDER BY NAME) AS NUMBER_ORDER, OCCUPATION, [NAME]
    	FROM OCCUPATIONS) AS TBL_SOURCE
PIVOT
(   MIN(NAME)
    FOR OCCUPATION
 	IN ([DOCTOR],[PROFESSOR],[SINGER],[ACTOR])
) AS TBL_PIVOT;
