WITH FILTERED_AND_RANKING_WANDS AS (
    SELECT  ROW_NUMBER() OVER(PARTITION BY WP.AGE, W.POWER ORDER BY W.COINS_NEEDED) AS ROW_NUM,
            W.ID,
            WP.AGE,
            W.COINS_NEEDED,
            W.POWER
    FROM WANDS AS W
    INNER JOIN WANDS_PROPERTY AS WP ON W.CODE = WP.CODE
    WHERE IS_EVIL = 0
)

SELECT ID, AGE, COINS_NEEDED, POWER
FROM FILTERED_AND_RANKING_WANDS
WHERE ROW_NUM = 1
ORDER BY POWER DESC, AGE DESC
