SELECT AVG_POPULATION
FROM
    (SELECT COUNT(*) AS COUNT_ALL_CITY,
            SUM(POPULATION) AS TOTAL_POPULATION,
            FLOOR((SUM(POPULATION) / COUNT(*))) AS AVG_POPULATION
    FROM CITY) AS TBL_TEMP;
