WITH TEMP AS (
    SELECT EMPLOYEE_ID, MONTHS, SALARY
    FROM EMPLOYEE
    WHERE   (SALARY*MONTHS) =
            (SELECT MAX(SALARY*MONTHS) FROM EMPLOYEE)
)

SELECT MAX(SALARY*MONTHS), COUNT(*)
FROM TEMP
