SELECT  CONTESTS.CONTEST_ID,
        CONTESTS.HACKER_ID,
        CONTESTS.NAME,
        SUM(TEMP1.TOTAL_SUBMISSIONS),
        SUM(TEMP1.TOTAL_ACCEPTED_SUBMISSIONS),
        SUM(TEMP2.TOTAL_VIEWS),
        SUM(TEMP2.TOTAL_UNIQUE_VIEWS)
FROM CONTESTS
INNER JOIN COLLEGES ON CONTESTS.CONTEST_ID = COLLEGES.CONTEST_ID
INNER JOIN CHALLENGES ON CHALLENGES.COLLEGE_ID = COLLEGES.COLLEGE_ID
LEFT JOIN   (SELECT SS.CHALLENGE_ID,
                    SUM(SS.TOTAL_SUBMISSIONS) AS TOTAL_SUBMISSIONS,
                    SUM(SS.total_accepted_submissions) AS TOTAL_ACCEPTED_SUBMISSIONS
             FROM SUBMISSION_STATS AS SS
             GROUP BY SS.CHALLENGE_ID) AS TEMP1
ON CHALLENGES.CHALLENGE_ID = TEMP1.CHALLENGE_ID
LEFT JOIN   (SELECT VS.CHALLENGE_ID,
                    SUM(VS.TOTAL_VIEWS) AS TOTAL_VIEWS,
                    SUM(VS.TOTAL_UNIQUE_VIEWS) AS TOTAL_UNIQUE_VIEWS
             FROM VIEW_STATS AS VS
             GROUP BY VS.CHALLENGE_ID) AS TEMP2
ON CHALLENGES.CHALLENGE_ID = TEMP2.CHALLENGE_ID
GROUP BY CONTESTS.CONTEST_ID, CONTESTS.HACKER_ID, CONTESTS.NAME
HAVING (SUM(TEMP1.TOTAL_SUBMISSIONS) +
       SUM(TEMP1.TOTAL_ACCEPTED_SUBMISSIONS) +
       SUM(TEMP2.TOTAL_VIEWS) +
       SUM(TEMP2.TOTAL_UNIQUE_VIEWS)) > 0
ORDER BY CONTESTS.CONTEST_ID;
