WITH START_DATE AS (
    SELECT START_DATE
    FROM PROJECTS
    WHERE START_DATE NOT IN (SELECT END_DATE FROM PROJECTS)
), END_DATE AS (
    SELECT END_DATE
    FROM PROJECTS
    WHERE END_DATE NOT IN (SELECT START_DATE FROM PROJECTS)
), JOIN_TABLE AS (
    SELECT S.START_DATE, MIN(END_DATE) AS END_DATE
    FROM START_DATE AS S
    LEFT JOIN END_DATE AS E
    ON S.START_DATE < E.END_DATE
    GROUP BY S.START_DATE
)
SELECT START_DATE, END_DATE
FROM
    (SELECT  *,
            DATEDIFF(DAY,START_DATE,END_DATE) AS PROJECT_DURATION
    FROM JOIN_TABLE) AS TEMP
ORDER BY PROJECT_DURATION, START_DATE
