WITH TEMP AS (
    SELECT H.HACKER_ID, H.NAME, COUNT(CHALLENGE_ID) AS CHALLENGE_CREATED
    FROM HACKERS AS H
    LEFT JOIN CHALLENGES AS C
    ON H.HACKER_ID = C.HACKER_ID
    GROUP BY H.HACKER_ID, H.NAME
)

SELECT HACKER_ID, NAME, CHALLENGE_CREATED
FROM TEMP
WHERE CHALLENGE_CREATED IN
    (SELECT CHALLENGE_CREATED
    FROM TEMP
    GROUP BY CHALLENGE_CREATED
    HAVING COUNT(CHALLENGE_CREATED) = 1 OR CHALLENGE_CREATED = (SELECT MAX(CHALLENGE_CREATED) FROM TEMP))
ORDER BY 3 DESC, 1
