SELECT 	    STUDENTS.NAME
FROM	 	STUDENTS
JOIN 		FRIENDS ON STUDENTS.ID = FRIENDS.ID
JOIN 		PACKAGES AS P1 ON STUDENTS.ID = P1.ID
JOIN 		PACKAGES AS P2 ON FRIENDS.FRIEND_ID = P2.ID
WHERE 	    P2.SALARY > P1.SALARY
ORDER BY 	P2.SALARY;
